LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := lab126.cpp
LOCAL_MODULE := libshim_lab126
LOCAL_SHARED_LIBRARIES := liblog
LOCAL_CFLAGS := -Wno-format-security -Wno-unused-parameter
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := atomic.cpp
LOCAL_MODULE := libshim_atomic
LOCAL_SHARED_LIBRARIES := libutilscallstack
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := ui.cpp
LOCAL_MODULE := libshim_ui
LOCAL_SHARED_LIBRARIES := libui
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := gui.cpp
LOCAL_MODULE := libshim_gui
LOCAL_SHARED_LIBRARIES := libgui
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := crypto.cpp
LOCAL_MODULE := libshim_crypto
LOCAL_SHARED_LIBRARIES := libcrypto
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := binder.cpp
LOCAL_MODULE := libshim_binder
LOCAL_SHARED_LIBRARIES := libbinder
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := media.cpp
LOCAL_MODULE := libshim_media
LOCAL_SHARED_LIBRARIES := libmedia libutils
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := sensor.cpp
LOCAL_MODULE := libshim_sensor
LOCAL_SHARED_LIBRARIES := libsensor libutils
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_CFLAGS += $(LIBLOG_CFLAGS)
LOCAL_MODULE := libshim_xlog
LOCAL_SRC_FILES := xlog.c
LOCAL_C_INCLUDES += system/core/include/
LOCAL_SHARED_LIBRARIES := libcutils liblog libutils libbinder
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libshim_camera
LOCAL_SRC_FILES := camera.cpp
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := audio/libaudio_shim.c
LOCAL_LDLIBS += -ldl
LOCAL_C_INCLUDES += external/tinyalsa/include system/core/include/cutils
LOCAL_SHARED_LIBRARIES := liblog libtinyalsa
LOCAL_MODULE := libshim_audio
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_SHARED_LIBRARY)
